feedme-swent-epfl/feedme-android

- app/build.gradle.kts
- app/src/androidTest/java/com/android/feedme/test/component/SmallCommentsTest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/android/feedme/ui/navigation/SmallCommentsDisplay.kt
Implements UI to display the comment on the profile page.
Acceptance Criteria : 
- Comments displayed in a Column fashion
- Each Comments card has : image + author name + title + description
> 44 implement UI for comments small thumbnails on profile page

- app/src/androidTest/java/com/android/feedme/screen/LandingScreen.kt
- app/src/androidTest/java/com/android/feedme/test/LandingTest.kt
- app/src/main/java/com/android/feedme/ui/LandingScreen.kt
I finished implementing the UI for the Search Bar, as well as the tests. 
The functionalities such as actually searching and filtering are still undefined though.
> Implementing the Search Bar + updating the Landing Page functions

- app/src/androidTest/java/com/android/feedme/screen/FriendsScreen.kt
- app/src/androidTest/java/com/android/feedme/test/auth/LoginTest.kt
- app/src/androidTest/java/com/android/feedme/test/ui/FriendsTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
- app/src/main/java/com/android/feedme/ui/profile/FollowersScreen.kt
- app/src/main/java/com/android/feedme/ui/profile/FriendsScreen.kt
- app/src/main/java/com/android/feedme/ui/profile/ProfileScreen.kt
- app/src/main/java/com/android/feedme/ui/theme/Color.kt
Code the Figma implementation with static content inside of the app
> Follower/Following UI

- app/src/androidTest/java/com/android/feedme/screen/FriendsScreen.kt
- app/src/androidTest/java/com/android/feedme/test/auth/LoginTest.kt
- app/src/androidTest/java/com/android/feedme/test/ui/FriendsTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/model/data/ProfileRepository.kt
- app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
- app/src/main/java/com/android/feedme/ui/profile/FollowersScreen.kt
- app/src/main/java/com/android/feedme/ui/profile/FriendsScreen.kt
- app/src/main/java/com/android/feedme/ui/profile/ProfileScreen.kt
- app/src/main/java/com/android/feedme/ui/profile/ProfileViewModel.kt
- app/src/main/java/com/android/feedme/ui/theme/Color.kt
The idea is to have a friend page (follower/following UI) that is dynamic and based on the friends stored on the firebase database
> 68 viewmodel for followerfollowing page

- .github/workflows/ci.yml
- app/src/androidTest/java/com/android/feedme/screen/EditProfileTestScreen.kt
- app/src/androidTest/java/com/android/feedme/test/ui/EditProfileTest.kt
- app/src/androidTest/java/com/android/feedme/test/ui/ProfileTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
- app/src/main/java/com/android/feedme/ui/profile/EditProfileScreen.kt
- app/src/main/java/com/android/feedme/ui/profile/ProfileScreen.kt
- app/src/main/java/com/android/feedme/ui/profile/ProfileViewModel.kt
This PR aim at making the Screen and the Logic to modify the User profile
> 66 code logic to edit user profile info

- app/src/main/java/com/android/feedme/ui/profile/ProfileViewModel.kt
Description : upon sign-in, the default profile is display instead of the database profile
Fix : add a listener
> Fixed a bug with ProfileViewModel

- app/src/main/java/com/android/feedme/ui/profile/ProfileViewModel.kt
Was missing a check if the list was null before querying the database leading to a crash
> Fix an issue with 0 followers

- app/src/androidTest/java/com/android/feedme/test/LandingTest.kt
- app/src/androidTest/java/com/android/feedme/test/component/SmallCommentsTest.kt
- app/src/androidTest/java/com/android/feedme/test/ui/FullRecipeTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/ui/component/SmallCommentsDisplay.kt
- app/src/main/java/com/android/feedme/ui/home/LandingScreen.kt
- app/src/main/java/com/android/feedme/ui/home/RecipeFullDisplay.kt
- app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
Added the navigation to FullRecipeScreen when clicking on a recipe in the LandingPage.
I added a temporary recipe for the moment in order to show it in the demo, will be removed once the RecipeViewModel is created.
> Navigation to FullRecipe

- app/src/androidTest/java/com/android/feedme/test/UserFlowTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/ui/CreateScreen.kt
- app/src/main/java/com/android/feedme/ui/auth/LoginScreen.kt
- app/src/main/java/com/android/feedme/ui/home/LandingScreen.kt
- app/src/main/java/com/android/feedme/ui/home/RecipeFullDisplay.kt
- app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
- app/src/main/java/com/android/feedme/ui/profile/ProfileScreen.kt
Modify the MainActivity to support nested navigation.
Fixed the Route object to include only the 6 main routes, other 'routes' were added to the Screen object.
Waiting for the RecipeViewModel to be implemented to fix navigation to FullRecipeDisplay.
> Implement NavHost as a Nested Graph

- .gitignore
- app/src/androidTest/java/com/android/feedme/screen/SettingsScreen.kt
- app/src/androidTest/java/com/android/feedme/test/NotImplementedTest.kt
- app/src/androidTest/java/com/android/feedme/test/ui/SettingsTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
- app/src/main/java/com/android/feedme/ui/settings/SettingsScreen.kt
Implemented the SignOut button in SettingsScreen and added a main test for display.
> SignOut button

- .github/workflows/apk.yml
- .github/workflows/ci.yml
- .gitignore
- app/build.gradle.kts
Release APK creation, self signed and ready to be used
> Self sign APK

- app/build.gradle.kts
- app/src/androidTest/java/com/android/feedme/test/camera/CameraTest.kt
- app/src/main/java/com/android/feedme/ML/Barcode.kt
- app/src/main/java/com/android/feedme/ui/camera/Camera.kt
- gradle/libs.versions.toml
> 107 implement ml kit for bar code recognition

- app/src/androidTest/java/com/android/feedme/screen/WelcomeScreen.kt
- app/src/androidTest/java/com/android/feedme/test/ui/WelcomePageTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/model/viewmodel/AuthViewModel.kt
- app/src/main/java/com/android/feedme/ui/auth/LoginScreen.kt
- app/src/main/java/com/android/feedme/ui/auth/WelcomeScreen.kt
- app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
- app/src/main/java/com/android/feedme/ui/theme/Color.kt
- app/src/test/java/com/android/feedme/ui/AuthViewModelTest.kt
This PR deals with the welcome page. 
It implements the UI of the Welcome Page, which pops up when a user first logs in and is not present in the database of profiles, and leads them to the editing page where they can edit the components of their profile
> UI and implementation of Welcome page and editing of profile at creation

- app/src/androidTest/java/com/android/feedme/screen/SettingsScreen.kt
- app/src/androidTest/java/com/android/feedme/test/ui/SettingsTest.kt
- app/src/main/java/com/android/feedme/ui/settings/SettingsScreen.kt
Implemented the Settings page according to the UI, along with the tests
> Settings page UI implemented

- app/src/main/java/com/android/feedme/MainActivity.kt
Bug ; Upon new sign-in, nothing is shown in landing page
Fix : ViewModel was created before the sign-in, hence was not able to fetch database upon init
> Create viewModel at the correct place

- .github/workflows/apk.yml
- app/src/main/java/com/android/feedme/model/viewmodel/AuthViewModel.kt
- app/src/main/java/com/android/feedme/model/viewmodel/GalleryViewModel.kt
- res/scrum_board_m2.tsv
Addition of SCRUM Board and demo video to res folder, bug fixes for gallery pictures and username in profile creation, details on APK workflow file
> Finalize M2 submission

- app/src/androidTest/java/com/android/feedme/screen/RecipeStepInputTestScreen.kt
- app/src/androidTest/java/com/android/feedme/test/ui/RecipeStepInputTest.kt
- app/src/main/java/com/android/feedme/ui/component/RecipeStepInput.kt
> 141 UI for recipe step creation

- app/src/androidTest/java/com/android/feedme/screen/RecipeStepInputTestScreen.kt
- app/src/androidTest/java/com/android/feedme/test/ui/RecipeStepInputTest.kt
- app/src/main/java/com/android/feedme/ui/component/RecipeStepInput.kt
> 146 viewmodel for input of recipe step creation

- app/src/main/java/com/android/feedme/ml/TextRecognition.kt
- app/src/main/java/com/android/feedme/ui/camera/Camera.kt
Goal : 
- Fix error messages to make them consistent and informative for user.
> 158 error handling mlkit

- app/src/androidTest/java/com/android/feedme/screen/LandingScreen.kt
- app/src/androidTest/java/com/android/feedme/test/LandingTest.kt
- app/src/androidTest/java/com/android/feedme/test/component/SearchBarTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/model/data/ProfileRepository.kt
- app/src/main/java/com/android/feedme/model/data/Recipe.kt
- app/src/main/java/com/android/feedme/model/data/RecipeRepository.kt
- app/src/main/java/com/android/feedme/model/viewmodel/HomeViewModel.kt
- app/src/main/java/com/android/feedme/ui/component/SearchBar.kt
- app/src/main/java/com/android/feedme/ui/home/LandingScreen.kt
- app/src/test/java/com/android/feedme/ui/HomeViewModelTest.kt
- app/src/test/java/com/android/feedme/ui/LandingViewModelTest.kt
~~[ ] Adapt the UI to support the searching of profiles and recipes.~~ As mentioned below this will be implemented in a future PR.
> Searchbar logic

- app/src/androidTest/java/com/android/feedme/screen/SearchScreen.kt
- app/src/androidTest/java/com/android/feedme/test/LandingTest.kt
- app/src/androidTest/java/com/android/feedme/test/component/SearchBarTest.kt
- app/src/androidTest/java/com/android/feedme/test/ui/FriendsTest.kt
- app/src/androidTest/java/com/android/feedme/test/ui/SearchScreenTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/model/viewmodel/HomeViewModel.kt
- app/src/main/java/com/android/feedme/model/viewmodel/SearchViewModel.kt
- app/src/main/java/com/android/feedme/ui/component/SearchBar.kt
- app/src/main/java/com/android/feedme/ui/home/LandingScreen.kt
- app/src/main/java/com/android/feedme/ui/home/SearchScreen.kt
- app/src/main/java/com/android/feedme/ui/navigation/NavigationActions.kt
- app/src/test/java/com/android/feedme/ui/ProfileViewModelTest.kt
- app/src/test/java/com/android/feedme/ui/SearchViewModelTest.kt
Implement the UI and the navigation for the searching feature.
> UI for SearchScreen

- app/src/androidTest/java/com/android/feedme/test/component/CreateCommentTest.kt
- app/src/main/java/com/android/feedme/ui/component/CreateComment.kt
- app/src/main/java/com/android/feedme/ui/settings/SettingsScreen.kt
**Creating a new comment on a recipe**
This PR's goal is to implement a composable component that'll pop-up once we want to enter a new comment on a recipe. 
I finished implementing the UI, for reviewers, here's what it looks like :) 
nb : The gray space ext to the star is where users are supposed to input their rating of the recipe.
> Commenting on a recipe : UI for the pop-up window

- app/src/androidTest/java/com/android/feedme/test/camera/CameraTest.kt
- app/src/androidTest/java/com/android/feedme/test/ui/ParsingTest.kt
- app/src/main/java/com/android/feedme/ml/Barcode.kt
- app/src/main/java/com/android/feedme/ml/TextRecognition.kt
- app/src/main/java/com/android/feedme/model/viewmodel/CameraViewModel.kt
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
> 144 parsing json files for ingredient input through barcode

- app/src/main/java/com/android/feedme/model/data/RecipeRepository.kt
- app/src/main/java/com/android/feedme/model/viewmodel/HomeViewModel.kt
- app/src/test/java/com/android/feedme/ui/SearchViewModelTest.kt
Weird bug that is not related to recent push but due to the database update.
Landing Page fetch some default recipe but they have been deleted.
The view model was wrongly coded to threw and error if a recipe is not found.
Replaced the threw with a Logging instead.
> BUG FIX : Crash on Start

- app/src/main/java/com/android/feedme/model/data/ProfileRepository.kt
- app/src/main/java/com/android/feedme/model/data/RecipeRepository.kt
- app/src/main/java/com/android/feedme/model/viewmodel/SearchViewModel.kt
- app/src/main/java/com/android/feedme/ui/home/SearchScreen.kt
- app/src/test/java/com/android/feedme/ui/SearchViewModelTest.kt
I modified the getFilteredRecipes and getFilteredProfiles methods in RecipeRepository and ProfileRepository respectively.
A limit of 10 was added for each call if these methods, and at the end of the screen I added a 'Load more' button to fetch 10 more Recipes/Profile (if available) when clicked.
> Database infinite query fix

- app/src/androidTest/java/com/android/feedme/test/camera/CameraTest.kt
- app/src/main/java/com/android/feedme/ml/TextRecognition.kt
- app/src/main/java/com/android/feedme/model/viewmodel/CameraViewModel.kt
- app/src/main/java/com/android/feedme/ui/camera/Camera.kt
Goals :
Requested changes inplemented : 
- Use vals to wrap error messages in the CameraViewModel.
> 178 UI for user interaction with ml camera module

- app/src/androidTest/java/com/android/feedme/test/ui/RecipeStepInputTest.kt
- app/src/main/java/com/android/feedme/ui/component/RecipeStepInput.kt
Due to re-computation of the step, the keyboard retract preventing to correctly input the step.
Add the re-computation upon losing focus instead that on every step
> Bug fix step input issue

- app/src/main/java/com/android/feedme/model/data/Ingredient.kt
- app/src/main/java/com/android/feedme/model/data/IngredientsRepository.kt
- app/src/main/java/com/android/feedme/model/data/RecipeRepository.kt
- app/src/test/java/com/android/feedme/model/IngredientsRepositoryTest.kt
- app/src/test/java/com/android/feedme/model/RecipeRepositoryTest.kt
Scenario : Upon visiting a full recipe, no ingredients appear... Yet they are well uploaded in the database....
What could be the bug?
> 224 bug  ingredients not displayed in full recipe screen

- app/src/main/java/com/android/feedme/ui/profile/ProfileScreen.kt
In order to fix the UI of the following button in Profile Screen, I added additional padding to main UI components in order to make the screen fit better any type of phone screen
> Fix the UI of following button in Profile Screen

- scraping/upload_img.py
Issue : our scrapped recipe does not have an image url...
This PR aim at finding a solution
> Fix add image url to database recipe

- app/src/androidTest/java/com/android/feedme/test/FindRecipeTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/model/data/Profile.kt
- app/src/main/java/com/android/feedme/model/data/ProfileRepository.kt
- app/src/main/java/com/android/feedme/model/viewmodel/ProfileViewModel.kt
- app/src/main/java/com/android/feedme/ui/find/FindRecipeScreen.kt
- app/src/test/java/com/android/feedme/ui/ProfileViewModelTest.kt
In this PR, I implemented UI of the popup for recipe generation. The text gives information to the user of the two ways to generate their recipes: 
- Strict : the user only generates recipes with those ingredients
- Extra : the user generated recipes that may contain additional ingredients compared to the ingredients inputted.
The popup has this appearance :
> Ingredient generation popup UI implementation

- app/src/androidTest/java/com/android/feedme/screen/SearchScreen.kt
- app/src/androidTest/java/com/android/feedme/test/ui/SearchScreenTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/model/data/ProfileRepository.kt
- app/src/main/java/com/android/feedme/model/data/Recipe.kt
- app/src/main/java/com/android/feedme/model/viewmodel/HomeViewModel.kt
- app/src/main/java/com/android/feedme/model/viewmodel/SearchViewModel.kt
- app/src/main/java/com/android/feedme/ui/home/LandingScreen.kt
- app/src/main/java/com/android/feedme/ui/home/SearchScreen.kt
This PR will solve the following fixes
> Search screen fixes

- app/src/main/java/com/android/feedme/model/data/IngredientsRepository.kt
- app/src/main/java/com/android/feedme/model/viewmodel/InputViewModel.kt
- app/src/main/java/com/android/feedme/ui/component/IngredientList.kt
- app/src/main/java/com/android/feedme/ui/generate/FindRecipeScreen.kt
- app/src/main/java/com/android/feedme/ui/theme/Color.kt
- app/src/test/java/com/android/feedme/ui/InputViewModelTest.kt
Cleaning up the IngredientList file to match the requirements in term of code complexity and fix UI bugs
**Complexity :**
** Bug Fix :**
> IngredientList bugs and reduce complexity update

- app/src/androidTest/java/com/android/feedme/test/component/CreateCommentTest.kt
- app/src/androidTest/java/com/android/feedme/test/ui/FullRecipeTest.kt
- app/src/main/java/com/android/feedme/MainActivity.kt
- app/src/main/java/com/android/feedme/model/data/Comment.kt
- app/src/main/java/com/android/feedme/model/data/CommentRepository.kt
- app/src/main/java/com/android/feedme/model/data/RecipeRepository.kt
- app/src/main/java/com/android/feedme/model/viewmodel/CameraViewModel.kt
- app/src/main/java/com/android/feedme/model/viewmodel/CommentViewModel.kt
- app/src/main/java/com/android/feedme/ui/component/CreateComment.kt
- app/src/main/java/com/android/feedme/ui/component/RecipeFullDisplay.kt
- app/src/test/java/com/android/feedme/model/CommentRepositoryTest.kt
This PR's aim is to implement the photo uploading to comments, so when a user comments on a recipe, they can add photos from their gallery to illustrate the results they got.
> Upload photo to the comments

- app/src/androidTest/java/com/android/feedme/screen/ProfileScreen.kt
- app/src/androidTest/java/com/android/feedme/test/ui/ProfileTest.kt
- app/src/main/java/com/android/feedme/ui/component/RecipeStepInput.kt
- app/src/main/java/com/android/feedme/ui/home/LandingScreen.kt
- app/src/main/java/com/android/feedme/ui/profile/ProfileScreen.kt
Small tasks to fix some UI issues :
> Small UI fixes part 2

- app/src/main/java/com/android/feedme/ui/profile/EditProfileScreen.kt
The picture was not updated properly because of a sync issue, it has been fixed
> Profile picture bug
